CREATE TABLE tb_caixa_eletronico (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE_NOTAS_CEM BIGINT NOT NULL,
QUANTIDADE_NOTAS_CINQUENTA BIGINT NOT NULL,
QUANTIDADE_NOTAS_VINTE BIGINT NOT NULL,
QUANTIDADE_NOTAS_DEZ BIGINT NOT NULL
);

INSERT INTO tb_caixa_eletronico(QUANTIDADE_NOTAS_CEM, QUANTIDADE_NOTAS_CINQUENTA, QUANTIDADE_NOTAS_VINTE, QUANTIDADE_NOTAS_DEZ)
VALUES(10, 10, 10, 10);